### ISSUE TITLE
I does not work right away

### ISSUE THREAD

**Issue by jmenzler** [yourtion/Alfred_SourceTree#1]
I installed the workflow but didn't manage it to work. Is there some setup routine required?

SourceTree v.2.3.2

**Comment by anortef** [comment]
Same here.

**Comment by anortef** [comment]
Ok, to fix it: 

Open alfred settings -> Workflows -> Right click on SourceTree workflow -> open in finder -> edit STP.py changing the line with the path to your correct path

**Comment by jmenzler** [comment]
Great, that worked! Thanks a lot! 👍

**Comment by mdeboer** [comment]
Same problem here, +1 on your PR @anortef 👍 , that fixes it!
