### ISSUE TITLE
Improve substring matching

### ISSUE THREAD

**Issue by mateatslc** [yourtion/Alfred_SourceTree#5]
When I search for `111`, I'd expect it to find not only stuff that starts with `111` but also anything that includes `111` _anywhere_ in the string, e.g. `asd111`, `a111ad`, etc.
I have a ton of projects prefixed with the same string so this would be a huge improvement.

**Comment by yourtion** [comment]
@mateatslc Already done. you can use https://github.com/yourtion/Alfred_SourceTree/releases/tag/1.1.0

**Comment by yourtion** [comment]
@mateatslc I implement for split `-`,`_`,` ` and camel_case project name. 
Because the filter is alfred match. so I think is ok for use now

![image](https://user-images.githubusercontent.com/1475301/31594316-cbd4c9f6-b1f9-11e7-8d43-74f0cba71ed3.png)

**Comment by mateatslc** [comment]
Works great, thanks!
